using System.Collections.Generic;

namespace VNTextPatch.Scripts.Softpal
{
    internal static class SoftpalOpcodes
    {
        public static readonly Dictionary<short, (string, string)> Descriptions =
            new Dictionary<short, (string, string)>
            {
                { 0x0001, ("mov", "pp") },
                { 0x0002, ("add", "pp") },
                { 0x0003, ("sub", "pp") },
                { 0x0004, ("mul", "pp") },
                { 0x0005, ("div", "pp") },
                { 0x0006, ("binand", "pp") },
                { 0x0007, ("binor", "pp") },
                { 0x0008, ("binxor", "pp") },
                { 0x0009, ("jmp", "l") },
                { 0x000A, ("jz", "lp") },
                { 0x000B, ("call", "l") },
                { 0x000C, ("eq", "pp") },
                { 0x000D, ("neq", "pp") },
                { 0x000E, ("le", "pp") },
                { 0x000F, ("ge", "pp") },
                { 0x0010, ("lt", "pp") },
                { 0x0011, ("gt", "pp") },
                { 0x0012, ("logor", "pp") },
                { 0x0013, ("logand", "pp") },
                { 0x0014, ("not", "i") },
                { 0x0015, ("exit", string.Empty) },
                { 0x0016, ("nop", string.Empty) },
                { 0x0017, ("syscall", "ii") },
                { 0x0018, ("ret", string.Empty) },
                { 0x0019, (null, string.Empty) },
                { 0x001A, ("mod", "pp") },
                { 0x001B, ("shl", "pp") },
                { 0x001C, ("sar", "pp") },
                { 0x001D, ("neg", "i") },
                { 0x001E, ("pop", "p") },
                { 0x001F, ("push", "p") },
                { 0x0020, ("enter", "p") },
                { 0x0021, ("leave", "p") },
                { 0x0023, ("create_message", string.Empty) },
                { 0x0024, ("get_message", string.Empty) },
                { 0x0025, ("get_message_param", string.Empty) },
                { 0x0028, ("se_load", string.Empty) },
                { 0x0029, ("se_play", string.Empty) },
                { 0x002A, ("se_play_ex", string.Empty) },
                { 0x002B, ("se_stop", string.Empty) },
                { 0x002C, ("se_set_volume", string.Empty) },
                { 0x002D, ("se_get_volume", string.Empty) },
                { 0x002E, ("se_unload", string.Empty) },
                { 0x002F, ("se_wait", string.Empty) },
                { 0x0030, ("set_se_info", string.Empty) },
                { 0x0031, ("get_se_ex_volume", string.Empty) },
                { 0x0032, ("set_se_ex_volume", string.Empty) },
                { 0x0033, ("se_enable", string.Empty) },
                { 0x0034, ("is_se_enable", string.Empty) },
                { 0x0035, ("se_set_pan", string.Empty) },
                { 0x0036, ("se_mute", string.Empty) },
                { 0x0038, ("select_init", string.Empty) },
                { 0x0039, ("select", string.Empty) },
                { 0x003A, ("select_add_choice", string.Empty) },
                { 0x003B, ("end_select", string.Empty) },
                { 0x003C, ("select_clear", string.Empty) },
                { 0x003D, ("select_set_offset", string.Empty) },
                { 0x003E, ("select_set_process", string.Empty) },
                { 0x003F, ("select_lock", string.Empty) },
                { 0x0040, ("get_select_on_key", string.Empty) },
                { 0x0041, ("get_select_pull_key", string.Empty) },
                { 0x0042, ("get_select_push_key", string.Empty) },
                { 0x0044, ("skip_set", string.Empty) },
                { 0x0045, ("skip_is", string.Empty) },
                { 0x0046, ("auto_set", string.Empty) },
                { 0x0047, ("auto_is", string.Empty) },
                { 0x0048, ("auto_set_time", string.Empty) },
                { 0x0049, ("auto_get_time", string.Empty) },
                { 0x004A, ("window_set_mode", string.Empty) },
                { 0x004B, (null, string.Empty) },
                { 0x004C, (null, string.Empty) },
                { 0x004D, (null, string.Empty) },
                { 0x004E, (null, string.Empty) },
                { 0x004F, ("effect_enable_is", string.Empty) },
                { 0x0050, ("cursor_pos_get", string.Empty) },
                { 0x0051, ("time_get", string.Empty) },
                { 0x0052, (null, string.Empty) },
                { 0x0053, ("load_font", string.Empty) },
                { 0x0054, ("unload_font", string.Empty) },
                { 0x0055, ("set_font_type", string.Empty) },
                { 0x0056, ("key_cancel", string.Empty) },
                { 0x0057, ("set_font_color", string.Empty) },
                { 0x0058, ("load_font_ex", string.Empty) },
                { 0x0059, (null, string.Empty) },
                { 0x005A, (null, string.Empty) },
                { 0x005B, ("lpush", string.Empty) }, // push label onto callstack
                { 0x005C, ("lpop", string.Empty) },
                { 0x005D, (null, string.Empty) },
                { 0x005E, (null, string.Empty) },
                { 0x005F, ("set_font_size", string.Empty) },
                { 0x0060, ("get_font_size", string.Empty) },
                { 0x0061, ("get_font_type", string.Empty) },
                { 0x0062, ("set_font_effect", string.Empty) },
                { 0x0063, ("get_font_effect", string.Empty) },
                { 0x0064, ("get_pull_key", string.Empty) },
                { 0x0065, ("get_on_key", string.Empty) },
                { 0x0066, ("get_push_key", string.Empty) },
                { 0x0067, ("input_clear", string.Empty) },
                { 0x0068, ("change_window_size", string.Empty) },
                { 0x0069, ("change_aspect_mode", string.Empty) },
                { 0x006A, ("aspect_position_enable", string.Empty) },
                { 0x006B, (null, string.Empty) },
                { 0x006C, ("get_aspect_mode", string.Empty) },
                { 0x006D, ("get_monitor_size", string.Empty) },
                { 0x006E, ("get_window_pos", string.Empty) },
                { 0x006F, ("get_system_metrics", string.Empty) },
                { 0x0070, ("set_system_path", string.Empty) },
                { 0x0071, ("set_allmosaicthumbnail", string.Empty) },
                { 0x0072, ("enable_window_change", string.Empty) },
                { 0x0073, ("is_enable_window_change", string.Empty) },
                { 0x0074, ("set_cursor", string.Empty) },
                { 0x0075, ("set_hide_cursor_time", string.Empty) },
                { 0x0076, ("get_hide_cursor_time", string.Empty) },
                { 0x0077, ("scene_skip", string.Empty) },
                { 0x0078, ("cancel_scene_skip", string.Empty) },
                { 0x0079, ("lsize", string.Empty) }, // get callstack size
                { 0x007A, ("get_async_key", string.Empty) },
                { 0x007B, ("get_font_color", string.Empty) },
                { 0x007C, ("get_current_date", string.Empty) },
                { 0x007D, ("history_skip", string.Empty) },
                { 0x007E, ("cancel_history_skip", string.Empty) },
                { 0x007F, (null, string.Empty) },
                { 0x0081, ("system_btn_set", string.Empty) },
                { 0x0082, ("system_btn_release", string.Empty) },
                { 0x0083, ("system_btn_enable", string.Empty) },
                { 0x0086, ("text_init", string.Empty) },
                { 0x0087, ("text_set_icon", string.Empty) },
                { 0x0088, ("text", string.Empty) },
                { 0x0089, ("text_hide", string.Empty) },
                { 0x008A, ("text_show", string.Empty) },
                { 0x008B, ("text_set_btn", string.Empty) },
                { 0x008C, ("text_uninit", string.Empty) },
                { 0x008D, ("text_set_rect", string.Empty) },
                { 0x008E, ("text_clear", string.Empty) },
                { 0x008F, (null, string.Empty) },
                { 0x0090, ("text_get_time", string.Empty) },
                { 0x0091, ("text_window_set_alpha", string.Empty) },
                { 0x0092, ("text_voice_play", string.Empty) },
                { 0x0093, (null, string.Empty) },
                { 0x0094, ("text_set_icon_animation_time", string.Empty) },
                { 0x0095, ("text_w", string.Empty) },
                { 0x0096, ("text_a", string.Empty) },
                { 0x0097, ("text_wa", string.Empty) },
                { 0x0098, ("text_n", string.Empty) },
                { 0x0099, ("text_cat", string.Empty) },
                { 0x009A, ("set_history", string.Empty) },
                { 0x009B, ("is_text_visible", string.Empty) },
                { 0x009C, ("text_set_base", string.Empty) },
                { 0x009D, ("enable_voice_cut", string.Empty) },
                { 0x009E, ("is_voice_cut", string.Empty) },
                { 0x009F, (null, string.Empty) },
                { 0x00A0, (null, string.Empty) },
                { 0x00A1, (null, string.Empty) },
                { 0x00A2, ("text_set_color", string.Empty) },
                { 0x00A3, ("text_redraw", string.Empty) },
                { 0x00A4, ("set_text_mode", string.Empty) },
                { 0x00A5, ("text_init_visualnovelmode", string.Empty) },
                { 0x00A6, ("text_set_icon_mode", string.Empty) },
                { 0x00A7, ("text_vn_br", string.Empty) },
                { 0x00A8, (null, string.Empty) },
                { 0x00A9, (null, string.Empty) },
                { 0x00AA, (null, string.Empty) },
                { 0x00AB, (null, string.Empty) },
                { 0x00AC, ("tips_get_str", string.Empty) },
                { 0x00AD, ("tips_get_param", string.Empty) },
                { 0x00AE, ("tips_reset", string.Empty) },
                { 0x00AF, ("tips_search", string.Empty) },
                { 0x00B0, ("tips_set_color", string.Empty) },
                { 0x00B1, ("tips_stop", string.Empty) },
                { 0x00B2, ("tips_get_flag", string.Empty) },
                { 0x00B3, ("tips_init", string.Empty) },
                { 0x00B4, ("tips_pause", string.Empty) },
                { 0x00B6, ("voice_play", string.Empty) },
                { 0x00B7, ("voice_stop", string.Empty) },
                { 0x00B8, ("voice_set_volume", string.Empty) },
                { 0x00B9, ("voice_get_volume", string.Empty) },
                { 0x00BA, ("set_voice_info", string.Empty) },
                { 0x00BB, ("voice_enable", string.Empty) },
                { 0x00BC, ("is_voice_enable", string.Empty) },
                { 0x00BD, (null, string.Empty) },
                { 0x00BE, ("bgv_play", string.Empty) },
                { 0x00BF, ("bgv_stop", string.Empty) },
                { 0x00C0, ("bgv_enable", string.Empty) },
                { 0x00C1, ("get_voice_ex_volume", string.Empty) },
                { 0x00C2, ("set_voice_ex_volume", string.Empty) },
                { 0x00C3, ("voice_check_enable", string.Empty) },
                { 0x00C4, ("voice_autopan_initialize", string.Empty) },
                { 0x00C5, ("voice_autopan_enable", string.Empty) },
                { 0x00C6, ("set_voice_autopan", string.Empty) },
                { 0x00C7, ("is_voice_autopan_enable", string.Empty) },
                { 0x00C8, ("voice_wait", string.Empty) },
                { 0x00C9, ("bgv_pause", string.Empty) },
                { 0x00CA, ("bgv_mute", string.Empty) },
                { 0x00CB, ("set_bgv_volume", string.Empty) },
                { 0x00CC, ("get_bgv_volume", string.Empty) },
                { 0x00CD, ("set_bgv_auto_volume", string.Empty) },
                { 0x00CE, ("voice_mute", string.Empty) },
                { 0x00CF, ("voice_call", string.Empty) },
                { 0x00D0, ("voice_call_clear", string.Empty) },
                { 0x00D2, ("wait", string.Empty) },
                { 0x00D3, ("wait_click", string.Empty) },
                { 0x00D4, ("wait_sync_begin", string.Empty) },
                { 0x00D5, ("wait_sync", string.Empty) },
                { 0x00D6, ("wait_sync_end", string.Empty) },
                { 0x00D7, (null, string.Empty) },
                { 0x00D8, ("wait_clear", string.Empty) },
                { 0x00D9, ("wait_click_no_anim", string.Empty) },
                { 0x00DA, ("wait_sync_get_time", string.Empty) },
                { 0x00DB, ("wait_time_push", string.Empty) },
                { 0x00DC, ("wait_time_pop", string.Empty) }
            };

        public const short Mov = 0x0001;
        public const short Call = 0x000B;
        public const short Syscall = 0x0017;
        public const short Ret = 0x0018;
        public const short Push = 0x001F;
        public const short Enter = 0x0020;
        public const short SelectAddChoice = 0x003A;
        public const short Text = 0x0088;
        public const short TextW = 0x0095;
        public const short TextA = 0x0096;
        public const short TextWA = 0x0097;
        public const short TextN = 0x0098;
        public const short TextCat = 0x0099;
    }
}
